export enum HttpStatus {
  OK = 200,
  Created = 201,
  AlreadyReported = 208,
  BadRequest = 400,
  Unauthorized = 401,
  Forbidden = 403,
  NotFound = 404,
  Conflict = 409,
  InternalServerError = 500,
  ServiceUnavailable = 503,
}

export enum ErrorCodes {
  RequestSignatureIsInvalid = 1,
  UserIsNotFound = 2,
  InvalidToken = 3,
  TokenIsOutOfDate = 4,
  RequestDataerror = 5,
  BetAmountIsNotSet = 6,
  NotEnoughMoney = 7,
  BetAlreadyProcessed = 8,
  UserIsBlocked = 9,
  UserStakeLimitHasBeenReached = 11,
  UserLossLimitHasBeenReached = 12,
  BetCountLimitHasBeenReached = 13,
  UserIsSelfExcluded = 14,
  UserIsNotVerified = 15,
  UserIsNotOldEnough = 16,
  RecalculationTransactionIsBlocked = 20,
  BonusTemplateIsNotFound = 30,
  BonusTemplateIsExpire = 31,
  BonusIsNotFound = 32,
  BonusIsNoActive = 33,
  BonusIsAlreadyActivated = 34,
  BonusIsAlreadyRevoked = 35,
  ErrorRevokeBonus = 36,
  SystemError = 100,
}

export enum CurrencyCodes {
  USD = 'USD',
  EUR = 'EUR',
  RUB = 'RUB',
  UAH = 'UAH',
  CNY = 'CNY',
  JPY = 'JPY',
  INR = 'INR',
  HTG = 'HTG',
  KZT = 'KZT',
  GBP = 'GBP',
  TRY = 'TRY',
  IRR = 'IRR',
  PEN = 'PEN',
  ARS = 'ARS',
  CLP = 'CLP',
  COP = 'COP',
  BOB = 'BOB',
  BRL = 'BRL',
  THB = 'THB',
  ARSB = 'ARSB',
  AFN = 'AFN',
  ETB = 'ETB',
  NGN = 'NGN',
  VND = 'VND',
  KRW = 'KRW',
  AZN = 'AZN',
  BBD = 'BBD',
  BDT = 'BDT',
  BIF = 'BIF',
  BWP = 'BWP',
  BYN = 'BYN',
  CUP = 'CUP',
  GEL = 'GEL',
  CHF = 'CHF',
  TND = 'TND',
  TJS = 'TJS',
  PHP = 'PHP',
}

export enum TransactionType {
  Bet = 1,
  Payment = 2,
  Rollback = 3,
}

export enum LocaleCodes {
  en = 'en',
  ru = 'ru',
  uk = 'uk',
  zh = 'zh',
  ja = 'ja',
  es = 'es',
  pt = 'pt',
  fr = 'fr',
  tr = 'tr',
  kk = 'kk',
  th = 'th',
  ko = 'ko',
  et = 'et',
  lt = 'lt',
  lv = 'lv',
}
